=== y1j2x34/StateMachine/target/test-classes/machine.dtd
<!ENTITY % link_attrs 
	"from CDATA #IMPLIED
	 to CDATA #IMPLIED
	 condition CDATA #IMPLIED
	 val CDATA #IMPLIED">

<!ELEMENT machine (import*,init,def,conf+,((cur?,listener?)|(listener?,cur?)))>
<!ELEMENT init (state)>
<!ELEMENT def (state*)>
<!ELEMENT state (action?,link*) >
<!ELEMENT conf (link+)>
<!ELEMENT link (property*)>
<!ELEMENT cur (#PCDATA)>
<!ELEMENT listener (property*)>
<!ELEMENT import (#PCDATA)>
<!ELEMENT property (#PCDATA)>
<!ELEMENT action (property*)>
<!ATTLIST machine judgement CDATA #IMPLIED>
<!ATTLIST state 
	name CDATA #REQUIRED
	action CDATA #IMPLIED
	>

<!ATTLIST conf %link_attrs;>

<!ATTLIST link %link_attrs;>

<!ATTLIST listener class CDATA #IMPLIED>
<!ATTLIST property name CDATA #REQUIRED >
<!ATTLIST property ref CDATA #IMPLIED >
<!ATTLIST property value CDATA #IMPLIED >
<!ATTLIST action class CDATA #IMPLIED>

=== y1j2x34/StateMachine/target/test-classes/machine.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE machine PUBLIC "" "src/test/resources/machine.dtd">
<machine>
	<import>y1j2x34.state.action.*</import>
	<import>y1j2x34.state.*</import>
	<init>
		<state name="walk" action="WalkSportAction"></state>
	</init>
	<def>
		<state name="run" action="RunSportAction"/>
		<state name="jump" action="JumpSportAction"/>
		<state name="dance" >
			<action class="DanceSportAction">
				<property name="danceName"/>
			</action>
		</state>
	</def>
	<conf val=".*" guards="RegexGuards" from="walk">
		<link to="run" val="\d+"/>
		<link to="jump" />
		<link to="dance" >
			<property name="haha" ref="haha"/>
		</link>
	</conf>
	
	<cur>dance</cur>
</machine>
